n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('É alfabético?', n.isalpha())
print('É numérico?', n.isnumeric())
print('Está em maiúsculo?', n.isupper())
print('Está em minúsculo?', n.islower())
print('Só tem espaços?', n.isspace())
print('É alfanumérico?', n.isalnum())
print('Está capitalizada?', n.istitle())
